# -*- coding: utf-8 -*-
"""DASHBOARD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fFVHv3w_1XXotbEFxqFV8JNaNo_ycfE
"""



import streamlit as st
import pandas as pd
import plotly.express as px

# Configuración de la página en modo ancho
st.set_page_config(page_title="NEXO Commerce Dashboard", layout="wide")

# Carga optimizada de datos
@st.cache_data
def load_data():
    try:
        df = pd.read_csv("dataset_limpio.csv")
        if 'order_date' in df.columns:
            df['order_date'] = pd.to_datetime(df['order_date'])
        return df
    except FileNotFoundError:
        st.error("No se encontró el archivo 'dataset_limpio.csv'. Por favor agrégalo al repositorio.")
        return pd.DataFrame()

df = load_data()

if not df.empty:
    # --- BARRA LATERAL: FILTROS ---
    st.sidebar.header("Filtros")

    # Filtro de País (Mapeado a las siglas de la captura: MX, CO, PE)
    if 'country' in df.columns:
        paises_disponibles = df['country'].unique()
        paises_seleccionados = st.sidebar.multiselect(
            "Filtrar por País",
            options=paises_disponibles,
            default=paises_disponibles
        )
    else:
        paises_seleccionados = []

    # Filtro de Segmento (Corregidos los errores de traducción del navegador)
    if 'segment' in df.columns:
        segmentos_disponibles = df['segment'].unique()
        segmentos_seleccionados = st.sidebar.multiselect(
            "Filtrar por Segmento",
            options=segmentos_disponibles,
            default=segmentos_disponibles
        )
    else:
        segmentos_seleccionados = []

    # Aplicar Filtros a la Base de Datos
    df_filtered = df[
        (df['country'].isin(paises_seleccionados)) &
        (df['segment'].isin(segmentos_seleccionados))
    ]

    # --- CUERPO PRINCIPAL ---
    st.title("📊 Panel de análisis de NEXO Commerce")
    st.write("Explora los datos interactivos de clientes, inventario y utilidad.")

    st.markdown("---")

    # --- SECCIÓN: MÉTRICAS PRINCIPALES ---
    st.header("Métricas Principales")
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        utilidad_total = df_filtered['profit'].sum() if 'profit' in df_filtered.columns else 0
        st.metric(label="Utilidad Total (Beneficio)", value=f"${utilidad_total:,.2f}")

    with col2:
        # En tu captura marcaba $0 porque faltaba la columna o el filtro la vació
        ventas_totales = df_filtered['total_sales'].sum() if 'total_sales' in df_filtered.columns else 0
        st.metric(label="Ventas Totales", value=f"${ventas_totales:,.2f}")

    with col3:
        ltv_promedio = df_filtered['ltv_predicted'].mean() if 'ltv_predicted' in df_filtered.columns else 0
        st.metric(label="LTV Promedio", value=f"${ltv_promedio:,.2f}")

    with col4:
        # "Acciones promedio" corregido a Stock Promedio
        stock_promedio = df_filtered['stock_level'].mean() if 'stock_level' in df_filtered.columns else 0
        st.metric(label="Stock Promedio", value=f"{stock_promedio:,.0f} und")

    st.markdown("---")

    # --- SECCIÓN: GRÁFICAS ---
    col_chart1, col_chart2 = st.columns(2)

    with col_chart1:
        st.subheader("📈 Evolución de Ventas")
        # Si no hay fechas o datos de tiempo, muestra la alerta azul idéntica a tu captura
        if 'order_date' not in df_filtered.columns or df_filtered.empty:
            st.info("Datos de fecha/precio no disponibles para gráfica.")
        else:
            df_trend = df_filtered.groupby('order_date')['profit'].sum().reset_index()
            fig_line = px.line(df_trend, x='order_date', y='profit', template="seaborn")
            st.plotly_chart(fig_line, use_container_width=True)

    with col_chart2:
        st.subheader("📦 Categorías principales: Ganancia vs Costo Inventario")
        if 'stock_level' in df_filtered.columns and 'profit' in df_filtered.columns:
            # Gráfica de dispersión basada en tus análisis multivariados previos
            fig_scatter = px.scatter(
                df_filtered,
                x="stock_level",
                y="profit",
                color="segment",
                labels={"stock_level": "Nivel de Stock", "profit": "Utilidad"},
                template="seaborn"
            )
            st.plotly_chart(fig_scatter, use_container_width=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # Configuración de la página en modo ancho
# st.set_page_config(page_title="NEXO Commerce Dashboard", layout="wide")
# 
# # Carga optimizada de datos
# @st.cache_data
# def load_data():
#     try:
#         df = pd.read_csv("dataset_limpio.csv")
#         if 'order_date' in df.columns:
#             df['order_date'] = pd.to_datetime(df['order_date'])
#         return df
#     except FileNotFoundError:
#         st.error("No se encontró el archivo 'dataset_limpio.csv'. Por favor agrégalo al repositorio.")
#         return pd.DataFrame()
# 
# df = load_data()
# 
# if not df.empty:
#     # --- BARRA LATERAL: FILTROS ---
#     st.sidebar.header("Filtros")
# 
#     # Filtro de País (Mapeado a las siglas de la captura: MX, CO, PE)
#     if 'country' in df.columns:
#         paises_disponibles = df['country'].unique()
#         paises_seleccionados = st.sidebar.multiselect(
#             "Filtrar por País",
#             options=paises_disponibles,
#             default=paises_disponibles
#         )
#     else:
#         paises_seleccionados = []
# 
#     # Filtro de Segmento (Corregidos los errores de traducción del navegador)
#     if 'segment' in df.columns:
#         segmentos_disponibles = df['segment'].unique()
#         segmentos_seleccionados = st.sidebar.multiselect(
#             "Filtrar por Segmento",
#             options=segmentos_disponibles,
#             default=segmentos_disponibles
#         )
#     else:
#         segmentos_seleccionados = []
# 
#     # Aplicar Filtros a la Base de Datos
#     df_filtered = df[
#         (df['country'].isin(paises_seleccionados)) &
#         (df['segment'].isin(segmentos_seleccionados))
#     ]
# 
#     # --- CUERPO PRINCIPAL ---
#     st.title("📊 Panel de análisis de NEXO Commerce")
#     st.write("Explora los datos interactivos de clientes, inventario y utilidad.")
# 
#     st.markdown("---")
# 
#     # --- SECCIÓN: MÉTRICAS PRINCIPALES ---
#     st.header("Métricas Principales")
#     col1, col2, col3, col4 = st.columns(4)
# 
#     with col1:
#         utilidad_total = df_filtered['profit'].sum() if 'profit' in df_filtered.columns else 0
#         st.metric(label="Utilidad Total (Beneficio)", value=f"${utilidad_total:,.2f}")
# 
#     with col2:
#         # En tu captura marcaba $0 porque faltaba la columna o el filtro la vació
#         ventas_totales = df_filtered['total_sales'].sum() if 'total_sales' in df_filtered.columns else 0
#         st.metric(label="Ventas Totales", value=f"${ventas_totales:,.2f}")
# 
#     with col3:
#         ltv_promedio = df_filtered['ltv_predicted'].mean() if 'ltv_predicted' in df_filtered.columns else 0
#         st.metric(label="LTV Promedio", value=f"${ltv_promedio:,.2f}")
# 
#     with col4:
#         # "Acciones promedio" corregido a Stock Promedio
#         stock_promedio = df_filtered['stock_level'].mean() if 'stock_level' in df_filtered.columns else 0
#         st.metric(label="Stock Promedio", value=f"{stock_promedio:,.0f} und")
# 
#     st.markdown("---")
# 
#     # --- SECCIÓN: GRÁFICAS ---
#     col_chart1, col_chart2 = st.columns(2)
# 
#     with col_chart1:
#         st.subheader("📈 Evolución de Ventas")
#         # Si no hay fechas o datos de tiempo, muestra la alerta azul idéntica a tu captura
#         if 'order_date' not in df_filtered.columns or df_filtered.empty:
#             st.info("Datos de fecha/precio no disponibles para gráfica.")
#         else:
#             df_trend = df_filtered.groupby('order_date')['profit'].sum().reset_index()
#             fig_line = px.line(df_trend, x='order_date', y='profit', template="seaborn")
#             st.plotly_chart(fig_line, use_container_width=True)
# 
#     with col_chart2:
#         st.subheader("📦 Categorías principales: Ganancia vs Costo Inventario")
#         if 'stock_level' in df_filtered.columns and 'profit' in df_filtered.columns:
#             # Gráfica de dispersión basada en tus análisis multivariados previos
#             fig_scatter = px.scatter(
#                 df_filtered,
#                 x="stock_level",
#                 y="profit",
#                 color="segment",
#                 labels={"stock_level": "Nivel de Stock", "profit": "Utilidad"},
#                 template="seaborn"
#             )
#             st.plotly_chart(fig_scatter, use_container_width=True)

# Install localtunnel to create a public URL for your Streamlit app
!npm install localtunnel

# Run Streamlit app and expose it via localtunnel


"""Now that `app.py` has been created, and assuming you have uploaded `dataset_limpio.csv` to your Colab environment, you can run your Streamlit application by following these steps:

1.  **Install `localtunnel`**: This tool will create a public URL for your Streamlit app running in Colab.
    ```bash
    !npm install localtunnel
    ```
2.  **Run Streamlit and `localtunnel`**: Execute the following command in a new code cell. This will start your Streamlit app and generate a public URL that you can open in your browser.
    ```bash
    !streamlit run app.py & npx localtunnel --port 8501
    ```

This will output a public URL in the cell's output. Copy and paste this URL into your web browser to view your Streamlit dashboard.
"""
